version: '3'
services:
  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=1080
    networks:
      - front
      - mailcatcher
    restart: always

networks:
  front:
    external:
      name: front
  mailcatcher:
    external:
      name: mailcatcher
